# Generated by Django 2.2 on 2019-04-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
