# Generated by Django 2.2.1 on 2019-05-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0002_auto_20190525_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tshirtapp.Customer', verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
