# Generated by Django 2.2.1 on 2019-05-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0003_auto_20190527_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tshirtapp.Tax', verbose_name='tax_id'),
        ),
    ]
