# Generated by Django 2.2.1 on 2019-05-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0004_auto_20190527_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tshirtapp.Shipping', verbose_name='shipping_id'),
        ),
    ]
